name: Deploy and Run

env:
  REPO_NAME: ${{ github.event.repository.name }}

on:
  workflow_dispatch:
  push:
    branches: [ main ]  # Agregué trigger automático

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Actualicé a v3
      
    - name: Login to Azure Container Registry
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.ACR_NAME }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker image
      run: |
        docker build . -t ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
        docker build . -t ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:latest  # Agregué tag latest
        docker push ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
        docker push ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Container Instances
      uses: azure/aci-deploy@v1
      with:
        location: eastus
        name: mielia-container
        resource-group: miel-ia
        image: ${{ secrets.ACR_NAME }}/${{ env.REPO_NAME }}:${{ github.sha }}
        dns-name-label: mielia-api-${{ github.run_id }}-${{ github.run_attempt }}
        registry-username: ${{ secrets.REGISTRY_USERNAME }}
        registry-password: ${{ secrets.REGISTRY_PASSWORD }}
        ports: 8000
        cpu: 2
        memory: 4

    - name: Logout
      run: az logout